baseURL: https://liriansu.com/
defaultContentLanguage: cn
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
languages:
  cn:
    contentDir: content/cn
    label: 中文
    locale: zh-CN
    weight: 1
  en:
    contentDir: content/en
    label: English
    locale: en-US
    weight: 2
params:
  author:
    name: Lirian Su
  headTitle: Lirian Su
  socials:
    - name: about
      link: /about
    - name: github
      link: https://github.com/liriansu-opus
    - name: zhihu
      link: https://www.zhihu.com/people/liriansu
    - name: rss
      link: /index.xml
theme: yinyang
title: 浮云计算
